### ISSUE TITLE
Removed getCore in ox_lib

### ISSUE THREAD

**Issue by Willem1981** [katotekii/Elevator-Script#2]
in ox_lib above v3.0.0 the getcore function is removed.
Now your scripts gives a error at start.

**Comment by katotekii** [comment]
done

**Comment by Willem1981** [comment]
Nice, very fast response.
It also gives a error on line 55.  Perhaps because of the core.PlayerData.job.name and the removal of the getCore.

**Comment by katotekii** [comment]
you should be good now

**Comment by Willem1981** [comment]
> you should be good now

No error anymore but also no marker. Could this be because of the ESX version? I have ESX 1.8.5
If i remove the job check then there is a marker and the elevator is working but no job check.

**Comment by katotekii** [comment]
noticed, looking at that now

**Comment by katotekii** [comment]
you should be good now

**Comment by Willem1981** [comment]
> you should be good now

Sir, you are a Legend. 👍
